# Generated by Django 5.2.8 on 2026-05-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='category_scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='parsed_data',
            field=models.JSONField(default=dict),
        ),
    ]
