# Generated by Django 5.2.8 on 2026-05-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysisreport_category_scores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisreport',
            name='parsed_data',
        ),
    ]
